apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.envVar.configmap }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}