apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.application }}
  name: {{ .Values.application }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.service.port }}-tcp
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.application }}
  type: {{ .Values.service.type }}