apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps
  namespace: argocd
spec:
  destination:
    # name: in-cluster
    server: https://kubernetes.default.svc
    namespace: test-apps
  source:
    targetRevision: HEAD
    repoURL: https://github.com/kalkantech/gitops-sample.git
    path: values/demo-spring/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default